version=1.0
environment=production
database.path=database.db
joystick.enabled=true
barcode_scanner.enabled=true
joystick.path=/dev/input/js0
barcode_scanner.path=/dev/input/event5

# The game is developed for a resolution of 1080p
# This means that all the assets are in this resolution
screen.height=1080
screen.width=1920
screen.scale=1
