version=1.0
environment=test
database.path=src/main/resources/database/test.db
joystick.path=pom.xml
barcode_scanner.path=pom.xml

# How long a game can take, before the "game over" screen appears
game.duration=30
